---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  # - name: ubuntu-16.04
  #   run_list:
  #   - recipe[apt]
  #   - recipe[curl]
  - name: centos-7.2
    run_list:
    - recipe[yum]
    - recipe[curl]

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[kibana_test::default]
